name: find_friends_02
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pycaret==3.3.2
      - python-dotenv
      - streamlit
      - pandas==1.5.3
      - openai
      - plotly